# Site settings
author: Jordan Long
title: if event_finder == cli_data_gem puts "My first project!"
header-img: img/home-bg.png
email: jordanleelong5@gmail.com
copyright_name: Jordan Long
description: > # this means to ignore newlines until "baseurl:"
  My CLI data gem portfolio project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: WebDevJordan
github_username:  JordanLong1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
